#!/bin/sh

exec 1>&2
json=$(jq '.' </dev/stdin)
path=$(echo "$json" | jq -r '.Upload.Storage.Path')
filename=$(echo "$json" | jq -r '.Upload.MetaData.filename')
dest="/complete/$filename"
mv "$path" "$dest"
