services:
  trunk:
    build: ./trunk
    command: [ "trunk", "build", "--release" ]
    working_dir: /ui
    environment:
    - CARGO_TARGET_DIR=/target
    volumes:
    - ./ui:/ui:rw
    - rust-cache:/target:rw
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    volumes:
    - config:/config:rw
    - complete:/downloads/complete:rw
    - incomplete:/downloads/incomplete:rw
  api:
    build:
      context: ./service
      dockerfile: Containerfile
    restart: always
    working_dir: /service
    volumes:
    - ./service:/service:rw
    - complete:/mkv:ro
    - webm:/webm:rw
    - gopath:/go:rw
    - gocache:/root/.cache/go:rw
  tusd:
    image: docker.io/tusproject/tusd:v1.9
    command: -behind-proxy -upload-dir=/data -hooks-dir=/hooks
    user: "0"
    volumes:
    - tusd-data:/data
    - complete:/complete
    - ./tusd:/hooks:ro
  nginx:
    image: docker.io/library/nginx:latest
    ports:
    - 8080:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./ui/dist:/www/data:ro
    - complete:/www/media/mkv:ro
    - webm:/www/media/webm:ro
    depends_on:
    - api
    - tusd
    - transmission

volumes:
  gopath:
  gocache:
  config:
  complete:
  incomplete:
  webm:
  rust-cache:
  tusd-data:
