services:
  trunk:
    build: ./trunk
    command: [ "trunk", "build", "--release" ]
    working_dir: /ui
    environment:
    - CARGO_TARGET_DIR=/target
    - RUSTFLAGS=--cfg=web_sys_unstable_apis
    volumes:
    - ./ui:/ui:rw
    - rust-cache:/target:rw
  # transmission:
  #   image: lscr.io/linuxserver/transmission:latest
  #   volumes:
  #   - data:/downloads/complete:rw
  #   - incomplete:/downloads/incomplete:rw
  #   - config:/config:rw
  api:
    build:
      context: ./api
      dockerfile: Containerfile.dev
    restart: always
    working_dir: /api
    environment:
    - MEDIA_SERVER_URL=http://localhost:8080/media
    volumes:
    - data:/data:ro
    - ./api:/api:rw
    - gopath:/go:rw
    - gocache:/root/.cache/go:rw
  tusd:
    image: docker.io/tusproject/tusd:v1.9
    command: -behind-proxy -upload-dir=/data -hooks-dir=/hooks
    user: "0"
    volumes:
    - data:/complete:rw
    - tusd-data:/data:rw
    - ./tusd:/hooks:ro
  nginx:
    image: docker.io/library/nginx:latest
    ports:
    - 8080:80
    volumes:
    - data:/www/media:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./ui/dist:/www/data:ro
    depends_on:
    - api
    - tusd
    # - transmission

volumes:
  gopath:
  gocache:
  config:
  incomplete:
  rust-cache:
  tusd-data:
  data:
  metadata:
