FROM docker.io/library/golang:alpine AS BUILDER

WORKDIR /src
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN go build -o /convert .


FROM docker.io/library/alpine:latest

RUN apk update && apk add ffmpeg
COPY --from=BUILDER /convert /convert

CMD [ "/convert" ]
